version: '3'
services:
  credit:
    build: ./springboot-credit-api
    ports:
      - "8050:8050"
    depends_on:
      - customer
      - product
  product:
    build: ./springboot-product-api
    ports:
      - "8020:8020"
    depends_on:
      - loanDb
  customer:
    build: ./springboot-customer-api
    ports:
      - "8010:8010"
    depends_on:
      - loanDb
  loanDb:
    container_name: 'loanDb'
    image: mysql
    environment:
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user
      MYSQL_DATABASE: loan_db
    ports:
      - "33060:3306"
    restart: always